apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: alice-demo-developer
  namespace: demo
  labels:
    owner: platform-team
    env: w10
subjects:
  - kind: User
    name: alice
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: demo-developer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bob-sre-pod-operator
  labels:
    owner: platform-team
    env: w10
subjects:
  - kind: User
    name: bob
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: w10-sre-pod-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: carol-cluster-viewer
  labels:
    owner: platform-team
    env: w10
subjects:
  - kind: User
    name: carol
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: w10-cluster-viewer
  apiGroup: rbac.authorization.k8s.io
