apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: w9-api-slo
  namespace: demo
  labels:
    app.kubernetes.io/name: w9-api
    app.kubernetes.io/part-of: w9-gitops-observability-canary
spec:
  groups:
    - name: w9-api.slo
      rules:
        - record: w9_api:slo_success_rate:2m
          expr: |
            (
              sum(rate(flask_http_request_total{namespace="demo",status!~"5.."}[2m]))
              /
              sum(rate(flask_http_request_total{namespace="demo"}[2m]))
            ) or vector(1)
        - alert: W9ApiHighErrorRate
          expr: |
            w9_api:slo_success_rate:2m < 0.98
          for: 1m
          labels:
            severity: warning
            slo: success-rate-98
          annotations:
            summary: W9 API error rate is higher than the 98% success SLO
            description: Success rate stayed below 98% for more than 1 minute.
