apiVersion: v1
kind: Service
metadata:
  name: w9-api
  namespace: demo
  labels:
    app.kubernetes.io/name: w9-api
    app.kubernetes.io/part-of: w9-gitops-observability-canary
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: w9-api
  ports:
    - name: http
      port: 80
      targetPort: http
